name: Build Macos Wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  macOS-latest-arm64:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel

      - name: Build Graph
        id: build-graph
        run: |
          python -m tn --text "2.5平方电线" --overwrite_cache
          python -m itn --text "二点五平方电线" --overwrite_cache

      - name: Prepare Graph
        id: prepare-graph
        run: |
          mkdir graph
          cp tn/*.fst graph
          cp itn/*.fst graph

      - name: Upload Graph
        id: upload-graph
        uses: actions/upload-artifact@v3
        with:
          name: release-graph-macos-amd64-v${{ github.event.inputs.version}}
          path: graph

  macOS-latest-x64:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel

      - name: Build Graph
        id: build-graph
        run: |
          python -m tn --text "2.5平方电线" --overwrite_cache
          python -m itn --text "二点五平方电线" --overwrite_cache

      - name: Prepare Graph
        id: prepare-graph
        run: |
          mkdir graph
          cp tn/*.fst graph
          cp itn/*.fst graph

      - name: Upload Graph
        id: upload-graph
        uses: actions/upload-artifact@v3
        with:
          name: release-graph-macos-x64-v${{ github.event.inputs.version}}
          path: graph